### PR TITLE
Build for more openssl variants

### PR DESCRIPTION
**Pull request by jdblischak**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

Follow up to https://github.com/conda-forge/azure-core-cpp-feedstock/pull/3 and https://github.com/conda-forge/azure-storage-common-cpp-feedstock/pull/5

Not immediately required for https://github.com/conda-forge/tiledb-feedstock/pull/205, but will eventually be once PR https://github.com/TileDB-Inc/TileDB/pull/4126 is merged

### CODE REVIEW

**Review by jjerphan — COMMENTED** [review]
No update to the recipe?

**Comment by jdblischak** [comment]
@jjerphan Good catch! I typically use `git commit -a`, but since `recipe/conda_build_config.yaml` was a new file, it wasn't included

**Comment by jjerphan** [comment]
It's fine. :)

**Comment by jdblischak** [comment]
@jjerphan could you please approve? Then we can label it `automerge`

**Review by jjerphan — APPROVED** [review]
LGTM after checking build variant you are using for TileDB.

Is [this syntax](https://github.com/conda-forge/tiledb-feedstock/blob/6d8607c89d1624d91ee8c8bc8897271eb9fd26f6/recipe/conda_build_config.yaml#L10-L17) uses to constraints pair of packages for a build.

**Comment by jdblischak** [comment]
> Is [this syntax](https://github.com/conda-forge/tiledb-feedstock/blob/6d8607c89d1624d91ee8c8bc8897271eb9fd26f6/recipe/conda_build_config.yaml#L10-L17) used to constrain pair of packages for builds?

Yes, along with `zip_keys`, this specifies 3 variants:

* openssl1+libcurl7+gcs_disabled
* openssl3+libcurl7+gcs_disabled
* openssl3+libcurl8+gcs_enabled

Without `zip_keys`, it would build all the combinations, which wouldn't work because openssl1 and libcurl8 can't be co-installed

```
mamba create --dry-run -n test libcurl=8 openssl=1

Looking for: ['libcurl=8', 'openssl=1']

bioconda/linux-64                                             No change
bioconda/noarch                                               No change
conda-forge/linux-64                                          No change
conda-forge/noarch                                  12.1MB @  10.6MB/s  1.2s
Could not solve for environment specs
The following packages are incompatible
├─ libcurl 8**  is installable with the potential options
│  ├─ libcurl [8.0.0|8.0.1|8.1.0|8.1.1|8.1.2] would require
│  │  └─ openssl >=3.1.0,<4.0a0 , which can be installed;
│  └─ libcurl [8.1.2|8.2.0|8.2.1] would require
│     └─ libssh2 >=1.11.0,<2.0a0 , which requires
│        └─ openssl >=3.1.1,<4.0a0 , which can be installed;
└─ openssl 1**  is not installable because it conflicts with any installable versions previously reported.
```

**Comment by jjerphan** [comment]
TIL that this specification exists. Thanks!

**Comment by jdblischak** [comment]
> TIL that this specification with `zip_keys` exists. Thanks!

You're welcome! Though I hope you never have to resort to using it :-)

The Azure recipes (and tiledb) aren't so bad because they don't involve Python. For Python recipes, trying to mess with `zip_keys` is more frustrating because [conda-forge-pinning](https://github.com/conda-forge/conda-forge-pinning-feedstock/blob/8e5d380c88035798d7ddf51bac64d7e20b1d4835/recipe/conda_build_config.yaml#L146) defines the `zip_keys` set `python`, `numpy`, and `python_impl`. Since the `zip_keys` don't merge well between conda-forge-pinning and a local `recipe/conda_build_config.yaml`, trying to use the `zip_keys` strategy to eg build different versions of Python with specific variants of other software is difficult.

**Pull request merged**
